### ISSUE TITLE
hello Here is my suggestion! Using  " torch_scatter()" rather than  "for loop"  during inference . 

### ISSUE THREAD

**Issue by lihaoming45** [zsef123/PointRend-PyTorch#5]
Example:                
   B,  D, H, W = pred.shape
    rend_pred = pred.view(B, C, -1).scatter_(2, rend_result['points'].unsqueeze(1).expand(-1, C, -1),
                                                         rend_result['rend'].float())
   rend_pred = rend_pred.reshape((B, C,  H, W))

**Comment by zsef123** [comment]
Thanks for your suggestion!!
I changed indexing.

**Comment by lihaoming45** [comment]
Thank you for the sharing! 


| |
lihao.ming
|
|
lihao.ming@163.com
|
签名由网易邮箱大师定制
On 1/18/2020 20:36，AhnDW<notifications@github.com> wrote：

Thanks for your suggestion!!
I changed indexing.
